// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -8; // objAA1Boss
global.__objectDepths[1] = 1025; // objAA1BossFutureBack
global.__objectDepths[2] = 0; // objAA1BossController
global.__objectDepths[3] = 1025; // objAA1BossPastBack
global.__objectDepths[4] = -9; // objAA1BossLaser
global.__objectDepths[5] = -5; // objAA1BossFloor
global.__objectDepths[6] = 1024; // objAA1BossFloorBack
global.__objectDepths[7] = 0; // objVV1Boss
global.__objectDepths[8] = 1; // objVV1BossBroken
global.__objectDepths[9] = 0; // objVV1BossController
global.__objectDepths[10] = 1; // objVV1BossFlyingPlatform
global.__objectDepths[11] = 10; // objVV1BossShield
global.__objectDepths[12] = 0; // objVV1BossSign
global.__objectDepths[13] = 1; // objEggWalker
global.__objectDepths[14] = -10; // objEggWalkerGun
global.__objectDepths[15] = -10; // objEggWalkerGunCover
global.__objectDepths[16] = -11; // objEggWalkerLaser
global.__objectDepths[17] = -10; // objEggWalkerLeg
global.__objectDepths[18] = 0; // objMoleEggWalker
global.__objectDepths[19] = 0; // objEggWalkerBossController
global.__objectDepths[20] = -1; // objEggWalkerMoleDeath
global.__objectDepths[21] = 0; // objEggWalkerBossSensor
global.__objectDepths[22] = -4; // objExplosionGroup
global.__objectDepths[23] = -4; // objExplosionGroupNoSound
global.__objectDepths[24] = 0; // objSmokeSpawn
global.__objectDepths[25] = -1; // objSmokePuff
global.__objectDepths[26] = 10; // objMegaTrooper
global.__objectDepths[27] = 0; // objMegaTrooperController
global.__objectDepths[28] = 4; // objMegaTrooperDriver
global.__objectDepths[29] = 1; // objMegaTrooperEye
global.__objectDepths[30] = 0; // objMegaTrooperHand
global.__objectDepths[31] = 3; // objMegaTrooperHead
global.__objectDepths[32] = 2; // objMegaTrooperJaw
global.__objectDepths[33] = -1; // objMegaTrooperMoleDeath
global.__objectDepths[34] = 4; // objMegaTrooperOrb
global.__objectDepths[35] = 5; // objMegaTrooperShoulder
global.__objectDepths[36] = 0; // objMegaTrooperGround
global.__objectDepths[37] = 0; // objMegaTrooperGroundPart
global.__objectDepths[38] = 6; // objMegaTrooperHeadBack
global.__objectDepths[39] = 5; // objWhaleBoss
global.__objectDepths[40] = 0; // objTTBossController
global.__objectDepths[41] = 4; // objWhaleBossJaw
global.__objectDepths[42] = 4; // objWhaleFin
global.__objectDepths[43] = 10; // objWhaleBossTowardsCam
global.__objectDepths[44] = 0; // objHarmfulBlock
global.__objectDepths[45] = -2; // objFireFlyLight
global.__objectDepths[46] = 0; // objFireFlyLightShot
global.__objectDepths[47] = 0; // objFireFlyBossController
global.__objectDepths[48] = 0; // objMetalSonicUFOs
global.__objectDepths[49] = 0; // objUFOAttack
global.__objectDepths[50] = 0; // objMetalSonicFlyOff
global.__objectDepths[51] = -1; // objFireFly
global.__objectDepths[52] = 1; // objFireFlyGraphic
global.__objectDepths[53] = -1024; // objMetallixController
global.__objectDepths[54] = 0; // objUFOAttackDD
global.__objectDepths[55] = 0; // objMetalClone
global.__objectDepths[56] = 0; // objUFOExplosion
global.__objectDepths[57] = 120; // objMetallixUFOBg
global.__objectDepths[58] = 1; // objMetallix
global.__objectDepths[59] = -1; // objMetallixPlatformHarmful
global.__objectDepths[60] = 1; // objMetallixPlatform
global.__objectDepths[61] = -1026; // objScoreCardFake
global.__objectDepths[62] = 0; // objMetallixHead
global.__objectDepths[63] = -11; // objMetallixLaser
global.__objectDepths[64] = 8; // objGalanik
global.__objectDepths[65] = 0; // objPPBossController
global.__objectDepths[66] = 7; // objGalanikNose
global.__objectDepths[67] = 1; // objBossPlatform
global.__objectDepths[68] = 2; // objPPGalanikLaser
global.__objectDepths[69] = 6; // objPPBossDisapearPlatform
global.__objectDepths[70] = 8; // objGalanikSmall
global.__objectDepths[71] = 0; // objUFOAttackPP
global.__objectDepths[72] = 5; // objMetalDamage
global.__objectDepths[73] = -1; // objPPBossFloor
global.__objectDepths[74] = 0; // objGalanikEyeShine
global.__objectDepths[75] = -2; // objLaserFire
global.__objectDepths[76] = 3; // objGalanikFireball
global.__objectDepths[77] = 1; // objFinalBossFace
global.__objectDepths[78] = 1; // objFinalBossArm
global.__objectDepths[79] = 2; // objFinalBoss
global.__objectDepths[80] = 2; // objFinalBossBackArm
global.__objectDepths[81] = 0; // objFinalBossFireball
global.__objectDepths[82] = 0; // objFinalBossFireBallStatic
global.__objectDepths[83] = 1; // objFinalBossFireballExhaust
global.__objectDepths[84] = 1000; // objFinalBossBackground
global.__objectDepths[85] = 0; // objFinalBossLaser
global.__objectDepths[86] = 1; // objRingDroppedFinalBoss
global.__objectDepths[87] = -1; // objLargeRockFinalBoss
global.__objectDepths[88] = 1; // objRingFinalBoss
global.__objectDepths[89] = 0; // objFinalBossController
global.__objectDepths[90] = 0; // objFinalBossPathControl
global.__objectDepths[91] = 0; // objGolemArm
global.__objectDepths[92] = 10; // objGolemHand
global.__objectDepths[93] = 128; // objGolemOrb
global.__objectDepths[94] = 0; // Object3D
global.__objectDepths[95] = 0; // objGolemSparks
global.__objectDepths[96] = -128; // objGolemTarget
global.__objectDepths[97] = 128; // objGolem
global.__objectDepths[98] = 0; // objExampleCollapsingPlatform
global.__objectDepths[99] = 0; // objExampleCollapsingPlatformPiece
global.__objectDepths[100] = 0; // objExampleMovingPlatformHorz
global.__objectDepths[101] = 0; // objMovingHorVerPlatform
global.__objectDepths[102] = 0; // objExampleMovingPlatformVert
global.__objectDepths[103] = -10; // objExampleBridge
global.__objectDepths[104] = 0; // objExamplePushable
global.__objectDepths[105] = 0; // objPushLog
global.__objectDepths[106] = -10; // objExampleQuicksand
global.__objectDepths[107] = 0; // objExampleBreakable
global.__objectDepths[108] = 0; // objExampleBreakableDebris
global.__objectDepths[109] = 0; // objSpring
global.__objectDepths[110] = 0; // objSpringGreen
global.__objectDepths[111] = 0; // objSpringDiagonal
global.__objectDepths[112] = 0; // objSpringRed
global.__objectDepths[113] = 0; // objSpringRedDiagonal
global.__objectDepths[114] = 12; // objSpringBlock
global.__objectDepths[115] = 0; // objHiddenSpring
global.__objectDepths[116] = 0; // objBlock
global.__objectDepths[117] = 0; // objCurveConcave
global.__objectDepths[118] = 0; // objCurveConcaveSlim
global.__objectDepths[119] = 0; // objCurveConvex
global.__objectDepths[120] = 0; // objCurveConvexSlim
global.__objectDepths[121] = 0; // objSlant
global.__objectDepths[122] = -1; // objCaterkiller
global.__objectDepths[123] = 0; // objCaterkillerOrb
global.__objectDepths[124] = 1; // objCaterminatorOrb
global.__objectDepths[125] = 0; // objCaterminator
global.__objectDepths[126] = 0; // objMoleGun
global.__objectDepths[127] = 0; // objMoleGunFire
global.__objectDepths[128] = 0; // obMoleGunGun
global.__objectDepths[129] = 0; // objMoleYoyo
global.__objectDepths[130] = 0; // objMoleYoyoYoyo
global.__objectDepths[131] = 0; // objOrbinaut
global.__objectDepths[132] = 0; // objOrbinautOrb
global.__objectDepths[133] = 0; // objPenguin
global.__objectDepths[134] = 0; // objRhinobot
global.__objectDepths[135] = 0; // objAntnik
global.__objectDepths[136] = 0; // objSealbot
global.__objectDepths[137] = 0; // objSealBomb
global.__objectDepths[138] = 0; // objWhalebot
global.__objectDepths[139] = 0; // objVutureBot
global.__objectDepths[140] = 0; // objEagleBot
global.__objectDepths[141] = 0; // objEagleBotIdle
global.__objectDepths[142] = 0; // objLaserGun
global.__objectDepths[143] = 0; // objLaserShot
global.__objectDepths[144] = -1; // objSmallBomb
global.__objectDepths[145] = 0; // objWallbot
global.__objectDepths[146] = 0; // objBigBombBadnik
global.__objectDepths[147] = 0; // objWaspBot
global.__objectDepths[148] = 0; // objDinobot
global.__objectDepths[149] = 1; // objFireRinobot
global.__objectDepths[150] = 0; // objFireTorch
global.__objectDepths[151] = -16; // objSauceroid
global.__objectDepths[152] = -16; // objSauceroidFire
global.__objectDepths[153] = -8; // objBubblesRegion
global.__objectDepths[154] = 0; // objBubblesBadnik
global.__objectDepths[155] = 0; // objSnailbot
global.__objectDepths[156] = -10; // objSnailTrail
global.__objectDepths[157] = -8; // objDragonFly
global.__objectDepths[158] = -1; // objDragonFlyBomb
global.__objectDepths[159] = -7; // objDragonFlySegment
global.__objectDepths[160] = 0; // objOstrich
global.__objectDepths[161] = -2; // objOstrichDibris
global.__objectDepths[162] = 3; // objOstrichHead
global.__objectDepths[163] = 0; // objFlowerShot
global.__objectDepths[164] = -2; // objFireball
global.__objectDepths[165] = -8; // objSquibotGun
global.__objectDepths[166] = 0; // objSquibot
global.__objectDepths[167] = -10; // objSquibotGunCover
global.__objectDepths[168] = -9; // objSquibotLaser
global.__objectDepths[169] = 1; // objRoboRex
global.__objectDepths[170] = 0; // objRoboRexHead
global.__objectDepths[171] = 10; // objRoboRexFoot
global.__objectDepths[172] = 0; // objRoboRexFrontFoot
global.__objectDepths[173] = 0; // objPterodactylBomb
global.__objectDepths[174] = 0; // objPterodactyl
global.__objectDepths[175] = 2; // objMoleFan
global.__objectDepths[176] = 0; // objEnemyTurn
global.__objectDepths[177] = -1; // objVVBomb
global.__objectDepths[178] = 0; // objVVBombExplosion
global.__objectDepths[179] = -1; // objVVBombLarge
global.__objectDepths[180] = 1; // objVVBombLauncher
global.__objectDepths[181] = 0; // objVVRhinobotSpawn
global.__objectDepths[182] = 0; // objVVRhinobotSpawnDebris
global.__objectDepths[183] = 10; // objVVShip
global.__objectDepths[184] = 10; // objVVShipLarge
global.__objectDepths[185] = 10; // objVVShipMedium
global.__objectDepths[186] = 10; // objVVShipMediumStationary
global.__objectDepths[187] = 0; // objVVMask01
global.__objectDepths[188] = -2; // objVVBushes
global.__objectDepths[189] = -2; // objVVLeaf
global.__objectDepths[190] = 0; // objVVPlatform
global.__objectDepths[191] = -1; // objVVBreakableWall
global.__objectDepths[192] = 0; // objVVBreakableWallDebris
global.__objectDepths[193] = 1; // objVVTileHole
global.__objectDepths[194] = -20; // objMetalThrow
global.__objectDepths[195] = -11; // objUFOFlame
global.__objectDepths[196] = 0; // objUFOLead
global.__objectDepths[197] = -10; // objUFO
global.__objectDepths[198] = 0; // objMetalThrowController
global.__objectDepths[199] = 0; // objOldManOwl
global.__objectDepths[200] = 0; // objVVFutureBack
global.__objectDepths[201] = 0; // objVVFutureBackAct2
global.__objectDepths[202] = 120; // objUFOBg
global.__objectDepths[203] = 0; // objVVPastBack
global.__objectDepths[204] = 0; // objVVPastBack2
global.__objectDepths[205] = 1023; // objVVPastBackSun
global.__objectDepths[206] = 1000; // objFFFutureBack
global.__objectDepths[207] = 1000; // objFFFutureBackAct2
global.__objectDepths[208] = 0; // objFFPastBack
global.__objectDepths[209] = 0; // objFFPastBackAct2
global.__objectDepths[210] = 0; // objArmor
global.__objectDepths[211] = 0; // objFFCollapsingPlatform
global.__objectDepths[212] = 0; // objFFCollapsingPlatformPiece
global.__objectDepths[213] = 0; // objFFOrb
global.__objectDepths[214] = 0; // objFFOrbLarge
global.__objectDepths[215] = 0; // objFFSnowFan
global.__objectDepths[216] = 2; // objSnowBlowerH
global.__objectDepths[217] = 0; // objSnowBlowerHTop
global.__objectDepths[218] = 2; // objSnowBlowerV
global.__objectDepths[219] = 0; // objSnowBlowerVTop
global.__objectDepths[220] = 1; // objSnowParticle
global.__objectDepths[221] = -20; // object178
global.__objectDepths[222] = -20; // objFFSnowEmitter
global.__objectDepths[223] = 0; // objFFSpikeball
global.__objectDepths[224] = 2; // objFFSwingWheel
global.__objectDepths[225] = 0; // objFFDropSpike
global.__objectDepths[226] = 4; // objFFIceSlip
global.__objectDepths[227] = 1; // objWarp
global.__objectDepths[228] = 0; // objBoard
global.__objectDepths[229] = 0; // objBoardExit
global.__objectDepths[230] = -1; // objFFLift
global.__objectDepths[231] = 1; // objAAShockSwingH
global.__objectDepths[232] = 1; // objAAShockSwingV
global.__objectDepths[233] = 2; // objAASwingWheel
global.__objectDepths[234] = 2; // objAATargetSwing
global.__objectDepths[235] = 0; // objAABobbin
global.__objectDepths[236] = 0; // objBallSplash
global.__objectDepths[237] = -1; // objAABoostWheel
global.__objectDepths[238] = 0; // objAADropBumper
global.__objectDepths[239] = 0; // objAAFlipper
global.__objectDepths[240] = 0; // objAAShockBumper
global.__objectDepths[241] = 0; // objAABumper
global.__objectDepths[242] = 0; // objInvisiblePlatform
global.__objectDepths[243] = 0; // objAABumperV
global.__objectDepths[244] = 0; // objAAShocker
global.__objectDepths[245] = 4; // objAASmasher
global.__objectDepths[246] = 4; // objAASmasherSmall
global.__objectDepths[247] = -2; // objAALampLight
global.__objectDepths[248] = 0; // objAATrampoline
global.__objectDepths[249] = -2; // objSlotMachine
global.__objectDepths[250] = 2; // objSlotMachineSolidMask
global.__objectDepths[251] = -1; // objAACloud2
global.__objectDepths[252] = -1; // objAACloud
global.__objectDepths[253] = 0; // objAAPlatform
global.__objectDepths[254] = 0; // objAAKnuckles
global.__objectDepths[255] = 0; // objAAPlane
global.__objectDepths[256] = 1; // objBGSlots
global.__objectDepths[257] = 0; // objAAFutureBack
global.__objectDepths[258] = 0; // objAAPastBack
global.__objectDepths[259] = 0; // object280
global.__objectDepths[260] = -1; // objAASpinner
global.__objectDepths[261] = 2; // objAAClock
global.__objectDepths[262] = 10; // objTubeWater
global.__objectDepths[263] = 0; // objTTSwingWhere
global.__objectDepths[264] = 0; // objCrate
global.__objectDepths[265] = 13; // objTTPWave
global.__objectDepths[266] = 0; // objFallingLog
global.__objectDepths[267] = 0; // objFallingLogVanish
global.__objectDepths[268] = -3; // objTTFMovingFloor
global.__objectDepths[269] = -3; // objTTFMovingFloorChild
global.__objectDepths[270] = 0; // objSpikeRoller
global.__objectDepths[271] = 1; // objWaterJet
global.__objectDepths[272] = 4; // objTTFFallingPlatform
global.__objectDepths[273] = 1; // objWaterJetTripple
global.__objectDepths[274] = 0; // objWaterJetEmmiter
global.__objectDepths[275] = 0; // objWaterJetEmmiterTripple
global.__objectDepths[276] = 0; // objSpikeRollerHarmful
global.__objectDepths[277] = -20; // objLillyPad
global.__objectDepths[278] = 0; // objTTPastBackParent
global.__objectDepths[279] = 1024; // objTTPastBack
global.__objectDepths[280] = 1024; // objTTPastBack2
global.__objectDepths[281] = 1024; // objTTFutureBack
global.__objectDepths[282] = 1024; // objTTFutureBack2
global.__objectDepths[283] = 1024; // objTTFutureRig
global.__objectDepths[284] = 1024; // objTTFutureRig2
global.__objectDepths[285] = 17; // objTTPastShip
global.__objectDepths[286] = 1024; // objTTPastShipMedium
global.__objectDepths[287] = 1024; // objTTPastShipSmall
global.__objectDepths[288] = 16; // objDynamoDeath
global.__objectDepths[289] = 0; // objDDFutureBack
global.__objectDepths[290] = 0; // objDDFutureBackAct2
global.__objectDepths[291] = 0; // objDDPastBack
global.__objectDepths[292] = 0; // objDDFutureIndoorBack
global.__objectDepths[293] = 0; // objDDFutureIndoorBackAct2
global.__objectDepths[294] = 1024; // objDDFutureBackSun
global.__objectDepths[295] = 1024; // objDDPSaturn
global.__objectDepths[296] = 0; // objPlaneGimmick
global.__objectDepths[297] = 2; // objSpikeRing
global.__objectDepths[298] = -2; // objDDLeaf
global.__objectDepths[299] = 0; // objPlaneStop
global.__objectDepths[300] = -1; // objSpinFlame
global.__objectDepths[301] = 0; // objSpinFlamesEmmit
global.__objectDepths[302] = 0; // objSpinFanHarmful
global.__objectDepths[303] = 0; // objDDFFanPlatform
global.__objectDepths[304] = 0; // objConveyor
global.__objectDepths[305] = -1; // objSand
global.__objectDepths[306] = 0; // objFan
global.__objectDepths[307] = 0; // objSkydive
global.__objectDepths[308] = 0; // objDDRockPiece
global.__objectDepths[309] = 1; // objDDFallingPlatform
global.__objectDepths[310] = 1; // objDDFallingPlatformSpawed
global.__objectDepths[311] = -1; // objDDBreakableRock
global.__objectDepths[312] = 9; // objSpinPoll
global.__objectDepths[313] = 9; // objSpinPollReverse
global.__objectDepths[314] = 8; // objPollPlatform
global.__objectDepths[315] = 8; // objPollPlatformReverse
global.__objectDepths[316] = 0; // objRolllingRock1
global.__objectDepths[317] = 0; // objRollingRock2
global.__objectDepths[318] = 0; // objRollingRockBarrior
global.__objectDepths[319] = -2048; // objMetalSonicCharge
global.__objectDepths[320] = 0; // objUFOCharge
global.__objectDepths[321] = 7; // objCapsule
global.__objectDepths[322] = 0; // objCapsuleDebris
global.__objectDepths[323] = 8; // objCapsuleGlass
global.__objectDepths[324] = -3; // objCapsuleSpark
global.__objectDepths[325] = 0; // objBoost
global.__objectDepths[326] = 0; // objCutscene
global.__objectDepths[327] = -50; // objField
global.__objectDepths[328] = 0; // objLayerFlip
global.__objectDepths[329] = 0; // objLayerSet
global.__objectDepths[330] = 0; // objPath
global.__objectDepths[331] = 0; // objGeneralTrigger
global.__objectDepths[332] = 0; // objBoss
global.__objectDepths[333] = 0; // objSpikeball
global.__objectDepths[334] = 0; // objEnemy
global.__objectDepths[335] = 3; // objIcon
global.__objectDepths[336] = 7; // objMonitorBroken
global.__objectDepths[337] = -10; // objBridge
global.__objectDepths[338] = 0; // objBumper
global.__objectDepths[339] = 0; // objFlower
global.__objectDepths[340] = 0; // objFlowerSpark
global.__objectDepths[341] = 0; // objScorePopup
global.__objectDepths[342] = 0; // objSwitch
global.__objectDepths[343] = 0; // objExplosionCluster
global.__objectDepths[344] = 0; // objExplosionSpecial
global.__objectDepths[345] = 0; // objRingDropped
global.__objectDepths[346] = 1; // objRingMagnetized
global.__objectDepths[347] = -1; // objBubble
global.__objectDepths[348] = 0; // objBubbleCluster
global.__objectDepths[349] = 16; // objWater
global.__objectDepths[350] = -8; // objLavaFountain
global.__objectDepths[351] = -7; // objLavaStream
global.__objectDepths[352] = 1; // objFallingPlatform
global.__objectDepths[353] = -8; // objWaterfall
global.__objectDepths[354] = 1; // objSignPost
global.__objectDepths[355] = 1; // objSignPostAct2
global.__objectDepths[356] = -2; // objMagnet
global.__objectDepths[357] = 0; // objSparkCannon
global.__objectDepths[358] = 0; // objSpark
global.__objectDepths[359] = -1; // objMagnetSparkle
global.__objectDepths[360] = 0; // objConveyerAngled
global.__objectDepths[361] = 1000; // objSSBack
global.__objectDepths[362] = 1025; // objSSZBGParallax2
global.__objectDepths[363] = 1025; // objSSZBGParallax
global.__objectDepths[364] = 1025; // objSSZBGParallax3
global.__objectDepths[365] = 1025; // objSSZBGParallax4
global.__objectDepths[366] = 4; // objFlippingPlatform
global.__objectDepths[367] = -1; // objShocker
global.__objectDepths[368] = -1; // objShockerTop
global.__objectDepths[369] = 0; // objSSPlatformVertical
global.__objectDepths[370] = 0; // objShockerLaser
global.__objectDepths[371] = 1; // objUFOFan
global.__objectDepths[372] = 1; // objPaddle
global.__objectDepths[373] = 0; // objPaddleSwitch
global.__objectDepths[374] = 1; // objPaddleTop
global.__objectDepths[375] = 0; // objSwitchButton
global.__objectDepths[376] = 0; // objPongController
global.__objectDepths[377] = -1; // objSSController
global.__objectDepths[378] = 1; // objSSMetalCut
global.__objectDepths[379] = 2; // objSSScreen
global.__objectDepths[380] = 0; // objSSRobotnik
global.__objectDepths[381] = 0; // objSwing
global.__objectDepths[382] = 1; // objAASwing
global.__objectDepths[383] = 0; // objRRBreakableColumn
global.__objectDepths[384] = 0; // objArrowChild
global.__objectDepths[385] = 1; // objArrowParent
global.__objectDepths[386] = 0; // objArrowSpawn
global.__objectDepths[387] = 0; // objRRPBack
global.__objectDepths[388] = 0; // objRRFBack
global.__objectDepths[389] = 1024; // objLittlePlanetPast
global.__objectDepths[390] = 1024; // objBigLittlePlanet
global.__objectDepths[391] = -1; // objCanon
global.__objectDepths[392] = -1; // objCanonSmoke
global.__objectDepths[393] = 0; // objRRWallRun
global.__objectDepths[394] = -1; // objGlassBottom
global.__objectDepths[395] = 0; // objGlassBreak
global.__objectDepths[396] = -1; // objGlassTop
global.__objectDepths[397] = 1024; // objPPBackEarth
global.__objectDepths[398] = 1000; // objPPBackground
global.__objectDepths[399] = 1026; // objNebula
global.__objectDepths[400] = -1; // objLargeRock
global.__objectDepths[401] = -1; // objSSLevelChunks
global.__objectDepths[402] = 0; // objSmallRock
global.__objectDepths[403] = -3; // objLavaCrack
global.__objectDepths[404] = 1; // objRockStairs
global.__objectDepths[405] = 0; // objLavaRock
global.__objectDepths[406] = -2; // objLavaSeep
global.__objectDepths[407] = 0; // objCrateLong
global.__objectDepths[408] = 0; // objFallingBlocks
global.__objectDepths[409] = -2; // objLava
global.__objectDepths[410] = 0; // objSingleFallBlock
global.__objectDepths[411] = 0; // objLavaTop
global.__objectDepths[412] = 0; // objBreakableRockBits
global.__objectDepths[413] = 0; // objBreakableRocks
global.__objectDepths[414] = -20; // objGalanikShadow
global.__objectDepths[415] = 0; // objScurge
global.__objectDepths[416] = 1; // objLampPost
global.__objectDepths[417] = 0; // objMonitor
global.__objectDepths[418] = 0; // objRing
global.__objectDepths[419] = 4; // objSpike
global.__objectDepths[420] = 0; // objSpikesNonSolid
global.__objectDepths[421] = 0; // objRingGiant
global.__objectDepths[422] = 4; // objTimePost
global.__objectDepths[423] = 0; // obj3dLayerFlip
global.__objectDepths[424] = -10; // objStart
global.__objectDepths[425] = 0; // objInputDummy
global.__objectDepths[426] = 0; // objInput
global.__objectDepths[427] = 0; // objGameData
global.__objectDepths[428] = 100; // objProgram
global.__objectDepths[429] = 0; // objMusic
global.__objectDepths[430] = 0; // objResources
global.__objectDepths[431] = -1024; // objScreen
global.__objectDepths[432] = 0; // objLogo
global.__objectDepths[433] = -1026; // objTitleControl
global.__objectDepths[434] = 3; // objTitleRing
global.__objectDepths[435] = -1; // objTitleRingOverlay
global.__objectDepths[436] = 1; // objTitleDynamo
global.__objectDepths[437] = 0; // objTitleSonic
global.__objectDepths[438] = -1; // objTitleCloud0
global.__objectDepths[439] = 3; // objTitleEffects
global.__objectDepths[440] = 4; // objTitleLighting
global.__objectDepths[441] = -1; // objTitleCloud1
global.__objectDepths[442] = 0; // objCharacterSelect
global.__objectDepths[443] = 0; // objLevelSelect
global.__objectDepths[444] = -1; // objSelector
global.__objectDepths[445] = 2; // objTitlescreenPlane
global.__objectDepths[446] = 20; // objTitleWater
global.__objectDepths[447] = -2048; // objFade
global.__objectDepths[448] = -2048; // objSSToLevel
global.__objectDepths[449] = -2048; // objLevelToSS
global.__objectDepths[450] = -2048; // objFadeWhite
global.__objectDepths[451] = -2048; // objFadeWhiteFromSave
global.__objectDepths[452] = -2048; // objEnterUFO
global.__objectDepths[453] = -2048; // objEnterFFZ
global.__objectDepths[454] = -2048; // objEnterTTZF
global.__objectDepths[455] = -2048; // objCloudTransition
global.__objectDepths[456] = -2048; // objTTZ2Transition
global.__objectDepths[457] = -1026; // objGameOver
global.__objectDepths[458] = -1025; // objTimeTravel
global.__objectDepths[459] = -2048; // objTitlecard
global.__objectDepths[460] = -2048; // objTitlecardDisolve
global.__objectDepths[461] = -2048; // objTitleCardSSZ
global.__objectDepths[462] = -2048; // objTitleCardFFZ
global.__objectDepths[463] = 0; // objTransition
global.__objectDepths[464] = -2048; // objSSZEndTransition
global.__objectDepths[465] = -2048; // objFinalEnding
global.__objectDepths[466] = -2048; // objEndingTransition
global.__objectDepths[467] = -1026; // objHud
global.__objectDepths[468] = 1024; // objParallax
global.__objectDepths[469] = -1026; // objThanksControl
global.__objectDepths[470] = -1026; // objScoreCard
global.__objectDepths[471] = 0; // objSaveSlot
global.__objectDepths[472] = 0; // objDeleteSlot
global.__objectDepths[473] = 0; // objSaveControl
global.__objectDepths[474] = 0; // obj3DSlant
global.__objectDepths[475] = 0; // objLevel
global.__objectDepths[476] = 0; // objSSPlayer
global.__objectDepths[477] = 101; // objSSCamera
global.__objectDepths[478] = 0; // Solid
global.__objectDepths[479] = 0; // objSSLevel
global.__objectDepths[480] = -5; // objSSCaterminatorOrb
global.__objectDepths[481] = 0; // objSSOrbinautOrb
global.__objectDepths[482] = 0; // objSSOrbinaut
global.__objectDepths[483] = 0; // obj3DExplosion
global.__objectDepths[484] = -5; // objSSCaterminator
global.__objectDepths[485] = 0; // objSSEnemy
global.__objectDepths[486] = 0; // objSSMoleMissile
global.__objectDepths[487] = 0; // objMissileFire
global.__objectDepths[488] = 0; // objSSMole
global.__objectDepths[489] = 0; // objSSWhalebot
global.__objectDepths[490] = -1026; // objSSHud
global.__objectDepths[491] = -1023; // objSSScoreCard
global.__objectDepths[492] = -1026; // objSSMessages
global.__objectDepths[493] = -1; // objSSRing
global.__objectDepths[494] = 0; // objSSRingFly
global.__objectDepths[495] = 0; // objSSBumper
global.__objectDepths[496] = 0; // objSSSpikeBall
global.__objectDepths[497] = -3; // objSSLargeSpike
global.__objectDepths[498] = -7; // objSSMetalSonic
global.__objectDepths[499] = 2; // obj3DShadow
global.__objectDepths[500] = -1; // objSSLife
global.__objectDepths[501] = 4000; // objTrack
global.__objectDepths[502] = 0; // objSSParent
global.__objectDepths[503] = 0; // objSSEnd
global.__objectDepths[504] = -1000; // objSSEmerald
global.__objectDepths[505] = 100; // objSSFutureTrack1_1
global.__objectDepths[506] = 100; // objSSFutureTrack1_2
global.__objectDepths[507] = 100; // objSSFutureTrack2_1
global.__objectDepths[508] = 100; // objSSFutureTrack2_2
global.__objectDepths[509] = 100; // objSSFutureTrack3_1
global.__objectDepths[510] = 100; // objSSFutureTrack3_2
global.__objectDepths[511] = 100; // objSSFutureTrack4_1
global.__objectDepths[512] = 100; // objSSFutureTrack4_2
global.__objectDepths[513] = 100; // objSSFutureTrack5_1
global.__objectDepths[514] = 100; // objSSFutureTrack5_2
global.__objectDepths[515] = 100; // objSSFutureTrack6_1
global.__objectDepths[516] = 100; // objSSFutureTrack6_2
global.__objectDepths[517] = 100; // objSSFutureTrack7_1
global.__objectDepths[518] = 100; // objSSFutureTrack7_2
global.__objectDepths[519] = 100; // objSSPastTrack1_1
global.__objectDepths[520] = 100; // objSSPastTrack1_2
global.__objectDepths[521] = 100; // objSSPastTrack2_1
global.__objectDepths[522] = 100; // objSSPastTrack2_2
global.__objectDepths[523] = 100; // objSSPastTrack3_1
global.__objectDepths[524] = 100; // objSSPastTrack3_2
global.__objectDepths[525] = 100; // objSSPastTrack4_1
global.__objectDepths[526] = 100; // objSSPastTrack4_2
global.__objectDepths[527] = 100; // objSSPastTrack5_1
global.__objectDepths[528] = 100; // objSSPastTrack5_2
global.__objectDepths[529] = 100; // objSSPastTrack6_1
global.__objectDepths[530] = 100; // objSSPastTrack6_2
global.__objectDepths[531] = 100; // objSSPastTrack7_1
global.__objectDepths[532] = 100; // objSSPastTrack7_2
global.__objectDepths[533] = 2000; // objSSPastTrack1BG
global.__objectDepths[534] = -1; // objSSBoost
global.__objectDepths[535] = 0; // objPathSplitStall
global.__objectDepths[536] = 0; // objNonSolid
global.__objectDepths[537] = 0; // objSceneObject
global.__objectDepths[538] = 0; // objSolid
global.__objectDepths[539] = 0; // objShieldIce
global.__objectDepths[540] = 0; // objShieldIceAttack
global.__objectDepths[541] = 0; // objShieldIceBlockDebris
global.__objectDepths[542] = 0; // objShieldBubble
global.__objectDepths[543] = 0; // objShieldFlame
global.__objectDepths[544] = 0; // objShieldLightning
global.__objectDepths[545] = 0; // objShieldWind
global.__objectDepths[546] = 0; // objShieldEarth
global.__objectDepths[547] = 0; // objShieldEarth_Rock
global.__objectDepths[548] = 0; // objDashSmoke
global.__objectDepths[549] = 0; // objInstaShield
global.__objectDepths[550] = 0; // objInvincibility
global.__objectDepths[551] = 0; // objShield
global.__objectDepths[552] = 0; // objTailsEffect
global.__objectDepths[553] = 0; // objFallHat
global.__objectDepths[554] = 0; // objCamera
global.__objectDepths[555] = 0; // objEffect
global.__objectDepths[556] = 0; // objPlayer
global.__objectDepths[557] = -2; // objDustCloud
global.__objectDepths[558] = 0; // objIntro1Control
global.__objectDepths[559] = 0; // objIntroClouds
global.__objectDepths[560] = 0; // objIntroIsland
global.__objectDepths[561] = 0; // objIntroLittlePlanet
global.__objectDepths[562] = -1; // objIntroMetalBack
global.__objectDepths[563] = 0; // objIntroMetalFly
global.__objectDepths[564] = -1; // objIntroMetalProfile
global.__objectDepths[565] = -1; // objIntroMetalZoom
global.__objectDepths[566] = 0; // objIntroSonicRunForward
global.__objectDepths[567] = 0; // objPyramid
global.__objectDepths[568] = 0; // objPyramidBack
global.__objectDepths[569] = 0; // objPyramidRotate
global.__objectDepths[570] = -4; // objMetalBackFull
global.__objectDepths[571] = -1; // objPyramidJump
global.__objectDepths[572] = 0; // objCutsceneController
global.__objectDepths[573] = 0; // objBadnikCutscene
global.__objectDepths[574] = 0; // objSonicLight
global.__objectDepths[575] = 0; // objTailsLight
global.__objectDepths[576] = 0; // objKnucklesLight
global.__objectDepths[577] = 0; // objSonicIntroPast
global.__objectDepths[578] = 0; // objKnucklesIntroPast
global.__objectDepths[579] = 0; // objTailsIntroPast
global.__objectDepths[580] = 0; // objIntroIslandPast
global.__objectDepths[581] = 0; // objRobotnikPastIntro
global.__objectDepths[582] = 0; // objDeathEggCut
global.__objectDepths[583] = 0; // objSmallSonic
global.__objectDepths[584] = 0; // objCutEmeralds
global.__objectDepths[585] = 0; // objSonicKnuckles
global.__objectDepths[586] = 0; // objTailsFlyCut
global.__objectDepths[587] = 0; // objMetalSonicWarped
global.__objectDepths[588] = 0; // objFadeInWhite
global.__objectDepths[589] = 10; // objTimeTravelVortex
global.__objectDepths[590] = 3; // objGalanikFloat
global.__objectDepths[591] = 4; // objCharacterFall
global.__objectDepths[592] = 1; // objLittlePlanetPiece1
global.__objectDepths[593] = 2; // objBiPlane
global.__objectDepths[594] = 0; // objCredits
global.__objectDepths[595] = 0; // objEndingClouds
global.__objectDepths[596] = 10; // objNeverLakeEnding
global.__objectDepths[597] = 2; // objPlaneRestoreFinal
global.__objectDepths[598] = 1; // objLittlePlanetPiece3
global.__objectDepths[599] = 1; // objLittlePlanetPiece2
global.__objectDepths[600] = 3; // objGalanikBadEnding
global.__objectDepths[601] = -1024; // objTextEnding
global.__objectDepths[602] = 0; // objTLPRestoreEnding
global.__objectDepths[603] = -50; // objMetalElectric
global.__objectDepths[604] = 6; // objAmyEnding
global.__objectDepths[605] = -20; // objEndingExplode
global.__objectDepths[606] = 0; // objGalacnikFootPart
global.__objectDepths[607] = 0; // objGalacnikStatchPart
global.__objectDepths[608] = 0; // objGalacnikHandPart


global.__objectNames[0] = "objAA1Boss";
global.__objectNames[1] = "objAA1BossFutureBack";
global.__objectNames[2] = "objAA1BossController";
global.__objectNames[3] = "objAA1BossPastBack";
global.__objectNames[4] = "objAA1BossLaser";
global.__objectNames[5] = "objAA1BossFloor";
global.__objectNames[6] = "objAA1BossFloorBack";
global.__objectNames[7] = "objVV1Boss";
global.__objectNames[8] = "objVV1BossBroken";
global.__objectNames[9] = "objVV1BossController";
global.__objectNames[10] = "objVV1BossFlyingPlatform";
global.__objectNames[11] = "objVV1BossShield";
global.__objectNames[12] = "objVV1BossSign";
global.__objectNames[13] = "objEggWalker";
global.__objectNames[14] = "objEggWalkerGun";
global.__objectNames[15] = "objEggWalkerGunCover";
global.__objectNames[16] = "objEggWalkerLaser";
global.__objectNames[17] = "objEggWalkerLeg";
global.__objectNames[18] = "objMoleEggWalker";
global.__objectNames[19] = "objEggWalkerBossController";
global.__objectNames[20] = "objEggWalkerMoleDeath";
global.__objectNames[21] = "objEggWalkerBossSensor";
global.__objectNames[22] = "objExplosionGroup";
global.__objectNames[23] = "objExplosionGroupNoSound";
global.__objectNames[24] = "objSmokeSpawn";
global.__objectNames[25] = "objSmokePuff";
global.__objectNames[26] = "objMegaTrooper";
global.__objectNames[27] = "objMegaTrooperController";
global.__objectNames[28] = "objMegaTrooperDriver";
global.__objectNames[29] = "objMegaTrooperEye";
global.__objectNames[30] = "objMegaTrooperHand";
global.__objectNames[31] = "objMegaTrooperHead";
global.__objectNames[32] = "objMegaTrooperJaw";
global.__objectNames[33] = "objMegaTrooperMoleDeath";
global.__objectNames[34] = "objMegaTrooperOrb";
global.__objectNames[35] = "objMegaTrooperShoulder";
global.__objectNames[36] = "objMegaTrooperGround";
global.__objectNames[37] = "objMegaTrooperGroundPart";
global.__objectNames[38] = "objMegaTrooperHeadBack";
global.__objectNames[39] = "objWhaleBoss";
global.__objectNames[40] = "objTTBossController";
global.__objectNames[41] = "objWhaleBossJaw";
global.__objectNames[42] = "objWhaleFin";
global.__objectNames[43] = "objWhaleBossTowardsCam";
global.__objectNames[44] = "objHarmfulBlock";
global.__objectNames[45] = "objFireFlyLight";
global.__objectNames[46] = "objFireFlyLightShot";
global.__objectNames[47] = "objFireFlyBossController";
global.__objectNames[48] = "objMetalSonicUFOs";
global.__objectNames[49] = "objUFOAttack";
global.__objectNames[50] = "objMetalSonicFlyOff";
global.__objectNames[51] = "objFireFly";
global.__objectNames[52] = "objFireFlyGraphic";
global.__objectNames[53] = "objMetallixController";
global.__objectNames[54] = "objUFOAttackDD";
global.__objectNames[55] = "objMetalClone";
global.__objectNames[56] = "objUFOExplosion";
global.__objectNames[57] = "objMetallixUFOBg";
global.__objectNames[58] = "objMetallix";
global.__objectNames[59] = "objMetallixPlatformHarmful";
global.__objectNames[60] = "objMetallixPlatform";
global.__objectNames[61] = "objScoreCardFake";
global.__objectNames[62] = "objMetallixHead";
global.__objectNames[63] = "objMetallixLaser";
global.__objectNames[64] = "objGalanik";
global.__objectNames[65] = "objPPBossController";
global.__objectNames[66] = "objGalanikNose";
global.__objectNames[67] = "objBossPlatform";
global.__objectNames[68] = "objPPGalanikLaser";
global.__objectNames[69] = "objPPBossDisapearPlatform";
global.__objectNames[70] = "objGalanikSmall";
global.__objectNames[71] = "objUFOAttackPP";
global.__objectNames[72] = "objMetalDamage";
global.__objectNames[73] = "objPPBossFloor";
global.__objectNames[74] = "objGalanikEyeShine";
global.__objectNames[75] = "objLaserFire";
global.__objectNames[76] = "objGalanikFireball";
global.__objectNames[77] = "objFinalBossFace";
global.__objectNames[78] = "objFinalBossArm";
global.__objectNames[79] = "objFinalBoss";
global.__objectNames[80] = "objFinalBossBackArm";
global.__objectNames[81] = "objFinalBossFireball";
global.__objectNames[82] = "objFinalBossFireBallStatic";
global.__objectNames[83] = "objFinalBossFireballExhaust";
global.__objectNames[84] = "objFinalBossBackground";
global.__objectNames[85] = "objFinalBossLaser";
global.__objectNames[86] = "objRingDroppedFinalBoss";
global.__objectNames[87] = "objLargeRockFinalBoss";
global.__objectNames[88] = "objRingFinalBoss";
global.__objectNames[89] = "objFinalBossController";
global.__objectNames[90] = "objFinalBossPathControl";
global.__objectNames[91] = "objGolemArm";
global.__objectNames[92] = "objGolemHand";
global.__objectNames[93] = "objGolemOrb";
global.__objectNames[94] = "Object3D";
global.__objectNames[95] = "objGolemSparks";
global.__objectNames[96] = "objGolemTarget";
global.__objectNames[97] = "objGolem";
global.__objectNames[98] = "objExampleCollapsingPlatform";
global.__objectNames[99] = "objExampleCollapsingPlatformPiece";
global.__objectNames[100] = "objExampleMovingPlatformHorz";
global.__objectNames[101] = "objMovingHorVerPlatform";
global.__objectNames[102] = "objExampleMovingPlatformVert";
global.__objectNames[103] = "objExampleBridge";
global.__objectNames[104] = "objExamplePushable";
global.__objectNames[105] = "objPushLog";
global.__objectNames[106] = "objExampleQuicksand";
global.__objectNames[107] = "objExampleBreakable";
global.__objectNames[108] = "objExampleBreakableDebris";
global.__objectNames[109] = "objSpring";
global.__objectNames[110] = "objSpringGreen";
global.__objectNames[111] = "objSpringDiagonal";
global.__objectNames[112] = "objSpringRed";
global.__objectNames[113] = "objSpringRedDiagonal";
global.__objectNames[114] = "objSpringBlock";
global.__objectNames[115] = "objHiddenSpring";
global.__objectNames[116] = "objBlock";
global.__objectNames[117] = "objCurveConcave";
global.__objectNames[118] = "objCurveConcaveSlim";
global.__objectNames[119] = "objCurveConvex";
global.__objectNames[120] = "objCurveConvexSlim";
global.__objectNames[121] = "objSlant";
global.__objectNames[122] = "objCaterkiller";
global.__objectNames[123] = "objCaterkillerOrb";
global.__objectNames[124] = "objCaterminatorOrb";
global.__objectNames[125] = "objCaterminator";
global.__objectNames[126] = "objMoleGun";
global.__objectNames[127] = "objMoleGunFire";
global.__objectNames[128] = "obMoleGunGun";
global.__objectNames[129] = "objMoleYoyo";
global.__objectNames[130] = "objMoleYoyoYoyo";
global.__objectNames[131] = "objOrbinaut";
global.__objectNames[132] = "objOrbinautOrb";
global.__objectNames[133] = "objPenguin";
global.__objectNames[134] = "objRhinobot";
global.__objectNames[135] = "objAntnik";
global.__objectNames[136] = "objSealbot";
global.__objectNames[137] = "objSealBomb";
global.__objectNames[138] = "objWhalebot";
global.__objectNames[139] = "objVutureBot";
global.__objectNames[140] = "objEagleBot";
global.__objectNames[141] = "objEagleBotIdle";
global.__objectNames[142] = "objLaserGun";
global.__objectNames[143] = "objLaserShot";
global.__objectNames[144] = "objSmallBomb";
global.__objectNames[145] = "objWallbot";
global.__objectNames[146] = "objBigBombBadnik";
global.__objectNames[147] = "objWaspBot";
global.__objectNames[148] = "objDinobot";
global.__objectNames[149] = "objFireRinobot";
global.__objectNames[150] = "objFireTorch";
global.__objectNames[151] = "objSauceroid";
global.__objectNames[152] = "objSauceroidFire";
global.__objectNames[153] = "objBubblesRegion";
global.__objectNames[154] = "objBubblesBadnik";
global.__objectNames[155] = "objSnailbot";
global.__objectNames[156] = "objSnailTrail";
global.__objectNames[157] = "objDragonFly";
global.__objectNames[158] = "objDragonFlyBomb";
global.__objectNames[159] = "objDragonFlySegment";
global.__objectNames[160] = "objOstrich";
global.__objectNames[161] = "objOstrichDibris";
global.__objectNames[162] = "objOstrichHead";
global.__objectNames[163] = "objFlowerShot";
global.__objectNames[164] = "objFireball";
global.__objectNames[165] = "objSquibotGun";
global.__objectNames[166] = "objSquibot";
global.__objectNames[167] = "objSquibotGunCover";
global.__objectNames[168] = "objSquibotLaser";
global.__objectNames[169] = "objRoboRex";
global.__objectNames[170] = "objRoboRexHead";
global.__objectNames[171] = "objRoboRexFoot";
global.__objectNames[172] = "objRoboRexFrontFoot";
global.__objectNames[173] = "objPterodactylBomb";
global.__objectNames[174] = "objPterodactyl";
global.__objectNames[175] = "objMoleFan";
global.__objectNames[176] = "objEnemyTurn";
global.__objectNames[177] = "objVVBomb";
global.__objectNames[178] = "objVVBombExplosion";
global.__objectNames[179] = "objVVBombLarge";
global.__objectNames[180] = "objVVBombLauncher";
global.__objectNames[181] = "objVVRhinobotSpawn";
global.__objectNames[182] = "objVVRhinobotSpawnDebris";
global.__objectNames[183] = "objVVShip";
global.__objectNames[184] = "objVVShipLarge";
global.__objectNames[185] = "objVVShipMedium";
global.__objectNames[186] = "objVVShipMediumStationary";
global.__objectNames[187] = "objVVMask01";
global.__objectNames[188] = "objVVBushes";
global.__objectNames[189] = "objVVLeaf";
global.__objectNames[190] = "objVVPlatform";
global.__objectNames[191] = "objVVBreakableWall";
global.__objectNames[192] = "objVVBreakableWallDebris";
global.__objectNames[193] = "objVVTileHole";
global.__objectNames[194] = "objMetalThrow";
global.__objectNames[195] = "objUFOFlame";
global.__objectNames[196] = "objUFOLead";
global.__objectNames[197] = "objUFO";
global.__objectNames[198] = "objMetalThrowController";
global.__objectNames[199] = "objOldManOwl";
global.__objectNames[200] = "objVVFutureBack";
global.__objectNames[201] = "objVVFutureBackAct2";
global.__objectNames[202] = "objUFOBg";
global.__objectNames[203] = "objVVPastBack";
global.__objectNames[204] = "objVVPastBack2";
global.__objectNames[205] = "objVVPastBackSun";
global.__objectNames[206] = "objFFFutureBack";
global.__objectNames[207] = "objFFFutureBackAct2";
global.__objectNames[208] = "objFFPastBack";
global.__objectNames[209] = "objFFPastBackAct2";
global.__objectNames[210] = "objArmor";
global.__objectNames[211] = "objFFCollapsingPlatform";
global.__objectNames[212] = "objFFCollapsingPlatformPiece";
global.__objectNames[213] = "objFFOrb";
global.__objectNames[214] = "objFFOrbLarge";
global.__objectNames[215] = "objFFSnowFan";
global.__objectNames[216] = "objSnowBlowerH";
global.__objectNames[217] = "objSnowBlowerHTop";
global.__objectNames[218] = "objSnowBlowerV";
global.__objectNames[219] = "objSnowBlowerVTop";
global.__objectNames[220] = "objSnowParticle";
global.__objectNames[221] = "object178";
global.__objectNames[222] = "objFFSnowEmitter";
global.__objectNames[223] = "objFFSpikeball";
global.__objectNames[224] = "objFFSwingWheel";
global.__objectNames[225] = "objFFDropSpike";
global.__objectNames[226] = "objFFIceSlip";
global.__objectNames[227] = "objWarp";
global.__objectNames[228] = "objBoard";
global.__objectNames[229] = "objBoardExit";
global.__objectNames[230] = "objFFLift";
global.__objectNames[231] = "objAAShockSwingH";
global.__objectNames[232] = "objAAShockSwingV";
global.__objectNames[233] = "objAASwingWheel";
global.__objectNames[234] = "objAATargetSwing";
global.__objectNames[235] = "objAABobbin";
global.__objectNames[236] = "objBallSplash";
global.__objectNames[237] = "objAABoostWheel";
global.__objectNames[238] = "objAADropBumper";
global.__objectNames[239] = "objAAFlipper";
global.__objectNames[240] = "objAAShockBumper";
global.__objectNames[241] = "objAABumper";
global.__objectNames[242] = "objInvisiblePlatform";
global.__objectNames[243] = "objAABumperV";
global.__objectNames[244] = "objAAShocker";
global.__objectNames[245] = "objAASmasher";
global.__objectNames[246] = "objAASmasherSmall";
global.__objectNames[247] = "objAALampLight";
global.__objectNames[248] = "objAATrampoline";
global.__objectNames[249] = "objSlotMachine";
global.__objectNames[250] = "objSlotMachineSolidMask";
global.__objectNames[251] = "objAACloud2";
global.__objectNames[252] = "objAACloud";
global.__objectNames[253] = "objAAPlatform";
global.__objectNames[254] = "objAAKnuckles";
global.__objectNames[255] = "objAAPlane";
global.__objectNames[256] = "objBGSlots";
global.__objectNames[257] = "objAAFutureBack";
global.__objectNames[258] = "objAAPastBack";
global.__objectNames[259] = "object280";
global.__objectNames[260] = "objAASpinner";
global.__objectNames[261] = "objAAClock";
global.__objectNames[262] = "objTubeWater";
global.__objectNames[263] = "objTTSwingWhere";
global.__objectNames[264] = "objCrate";
global.__objectNames[265] = "objTTPWave";
global.__objectNames[266] = "objFallingLog";
global.__objectNames[267] = "objFallingLogVanish";
global.__objectNames[268] = "objTTFMovingFloor";
global.__objectNames[269] = "objTTFMovingFloorChild";
global.__objectNames[270] = "objSpikeRoller";
global.__objectNames[271] = "objWaterJet";
global.__objectNames[272] = "objTTFFallingPlatform";
global.__objectNames[273] = "objWaterJetTripple";
global.__objectNames[274] = "objWaterJetEmmiter";
global.__objectNames[275] = "objWaterJetEmmiterTripple";
global.__objectNames[276] = "objSpikeRollerHarmful";
global.__objectNames[277] = "objLillyPad";
global.__objectNames[278] = "objTTPastBackParent";
global.__objectNames[279] = "objTTPastBack";
global.__objectNames[280] = "objTTPastBack2";
global.__objectNames[281] = "objTTFutureBack";
global.__objectNames[282] = "objTTFutureBack2";
global.__objectNames[283] = "objTTFutureRig";
global.__objectNames[284] = "objTTFutureRig2";
global.__objectNames[285] = "objTTPastShip";
global.__objectNames[286] = "objTTPastShipMedium";
global.__objectNames[287] = "objTTPastShipSmall";
global.__objectNames[288] = "objDynamoDeath";
global.__objectNames[289] = "objDDFutureBack";
global.__objectNames[290] = "objDDFutureBackAct2";
global.__objectNames[291] = "objDDPastBack";
global.__objectNames[292] = "objDDFutureIndoorBack";
global.__objectNames[293] = "objDDFutureIndoorBackAct2";
global.__objectNames[294] = "objDDFutureBackSun";
global.__objectNames[295] = "objDDPSaturn";
global.__objectNames[296] = "objPlaneGimmick";
global.__objectNames[297] = "objSpikeRing";
global.__objectNames[298] = "objDDLeaf";
global.__objectNames[299] = "objPlaneStop";
global.__objectNames[300] = "objSpinFlame";
global.__objectNames[301] = "objSpinFlamesEmmit";
global.__objectNames[302] = "objSpinFanHarmful";
global.__objectNames[303] = "objDDFFanPlatform";
global.__objectNames[304] = "objConveyor";
global.__objectNames[305] = "objSand";
global.__objectNames[306] = "objFan";
global.__objectNames[307] = "objSkydive";
global.__objectNames[308] = "objDDRockPiece";
global.__objectNames[309] = "objDDFallingPlatform";
global.__objectNames[310] = "objDDFallingPlatformSpawed";
global.__objectNames[311] = "objDDBreakableRock";
global.__objectNames[312] = "objSpinPoll";
global.__objectNames[313] = "objSpinPollReverse";
global.__objectNames[314] = "objPollPlatform";
global.__objectNames[315] = "objPollPlatformReverse";
global.__objectNames[316] = "objRolllingRock1";
global.__objectNames[317] = "objRollingRock2";
global.__objectNames[318] = "objRollingRockBarrior";
global.__objectNames[319] = "objMetalSonicCharge";
global.__objectNames[320] = "objUFOCharge";
global.__objectNames[321] = "objCapsule";
global.__objectNames[322] = "objCapsuleDebris";
global.__objectNames[323] = "objCapsuleGlass";
global.__objectNames[324] = "objCapsuleSpark";
global.__objectNames[325] = "objBoost";
global.__objectNames[326] = "objCutscene";
global.__objectNames[327] = "objField";
global.__objectNames[328] = "objLayerFlip";
global.__objectNames[329] = "objLayerSet";
global.__objectNames[330] = "objPath";
global.__objectNames[331] = "objGeneralTrigger";
global.__objectNames[332] = "objBoss";
global.__objectNames[333] = "objSpikeball";
global.__objectNames[334] = "objEnemy";
global.__objectNames[335] = "objIcon";
global.__objectNames[336] = "objMonitorBroken";
global.__objectNames[337] = "objBridge";
global.__objectNames[338] = "objBumper";
global.__objectNames[339] = "objFlower";
global.__objectNames[340] = "objFlowerSpark";
global.__objectNames[341] = "objScorePopup";
global.__objectNames[342] = "objSwitch";
global.__objectNames[343] = "objExplosionCluster";
global.__objectNames[344] = "objExplosionSpecial";
global.__objectNames[345] = "objRingDropped";
global.__objectNames[346] = "objRingMagnetized";
global.__objectNames[347] = "objBubble";
global.__objectNames[348] = "objBubbleCluster";
global.__objectNames[349] = "objWater";
global.__objectNames[350] = "objLavaFountain";
global.__objectNames[351] = "objLavaStream";
global.__objectNames[352] = "objFallingPlatform";
global.__objectNames[353] = "objWaterfall";
global.__objectNames[354] = "objSignPost";
global.__objectNames[355] = "objSignPostAct2";
global.__objectNames[356] = "objMagnet";
global.__objectNames[357] = "objSparkCannon";
global.__objectNames[358] = "objSpark";
global.__objectNames[359] = "objMagnetSparkle";
global.__objectNames[360] = "objConveyerAngled";
global.__objectNames[361] = "objSSBack";
global.__objectNames[362] = "objSSZBGParallax2";
global.__objectNames[363] = "objSSZBGParallax";
global.__objectNames[364] = "objSSZBGParallax3";
global.__objectNames[365] = "objSSZBGParallax4";
global.__objectNames[366] = "objFlippingPlatform";
global.__objectNames[367] = "objShocker";
global.__objectNames[368] = "objShockerTop";
global.__objectNames[369] = "objSSPlatformVertical";
global.__objectNames[370] = "objShockerLaser";
global.__objectNames[371] = "objUFOFan";
global.__objectNames[372] = "objPaddle";
global.__objectNames[373] = "objPaddleSwitch";
global.__objectNames[374] = "objPaddleTop";
global.__objectNames[375] = "objSwitchButton";
global.__objectNames[376] = "objPongController";
global.__objectNames[377] = "objSSController";
global.__objectNames[378] = "objSSMetalCut";
global.__objectNames[379] = "objSSScreen";
global.__objectNames[380] = "objSSRobotnik";
global.__objectNames[381] = "objSwing";
global.__objectNames[382] = "objAASwing";
global.__objectNames[383] = "objRRBreakableColumn";
global.__objectNames[384] = "objArrowChild";
global.__objectNames[385] = "objArrowParent";
global.__objectNames[386] = "objArrowSpawn";
global.__objectNames[387] = "objRRPBack";
global.__objectNames[388] = "objRRFBack";
global.__objectNames[389] = "objLittlePlanetPast";
global.__objectNames[390] = "objBigLittlePlanet";
global.__objectNames[391] = "objCanon";
global.__objectNames[392] = "objCanonSmoke";
global.__objectNames[393] = "objRRWallRun";
global.__objectNames[394] = "objGlassBottom";
global.__objectNames[395] = "objGlassBreak";
global.__objectNames[396] = "objGlassTop";
global.__objectNames[397] = "objPPBackEarth";
global.__objectNames[398] = "objPPBackground";
global.__objectNames[399] = "objNebula";
global.__objectNames[400] = "objLargeRock";
global.__objectNames[401] = "objSSLevelChunks";
global.__objectNames[402] = "objSmallRock";
global.__objectNames[403] = "objLavaCrack";
global.__objectNames[404] = "objRockStairs";
global.__objectNames[405] = "objLavaRock";
global.__objectNames[406] = "objLavaSeep";
global.__objectNames[407] = "objCrateLong";
global.__objectNames[408] = "objFallingBlocks";
global.__objectNames[409] = "objLava";
global.__objectNames[410] = "objSingleFallBlock";
global.__objectNames[411] = "objLavaTop";
global.__objectNames[412] = "objBreakableRockBits";
global.__objectNames[413] = "objBreakableRocks";
global.__objectNames[414] = "objGalanikShadow";
global.__objectNames[415] = "objScurge";
global.__objectNames[416] = "objLampPost";
global.__objectNames[417] = "objMonitor";
global.__objectNames[418] = "objRing";
global.__objectNames[419] = "objSpike";
global.__objectNames[420] = "objSpikesNonSolid";
global.__objectNames[421] = "objRingGiant";
global.__objectNames[422] = "objTimePost";
global.__objectNames[423] = "obj3dLayerFlip";
global.__objectNames[424] = "objStart";
global.__objectNames[425] = "objInputDummy";
global.__objectNames[426] = "objInput";
global.__objectNames[427] = "objGameData";
global.__objectNames[428] = "objProgram";
global.__objectNames[429] = "objMusic";
global.__objectNames[430] = "objResources";
global.__objectNames[431] = "objScreen";
global.__objectNames[432] = "objLogo";
global.__objectNames[433] = "objTitleControl";
global.__objectNames[434] = "objTitleRing";
global.__objectNames[435] = "objTitleRingOverlay";
global.__objectNames[436] = "objTitleDynamo";
global.__objectNames[437] = "objTitleSonic";
global.__objectNames[438] = "objTitleCloud0";
global.__objectNames[439] = "objTitleEffects";
global.__objectNames[440] = "objTitleLighting";
global.__objectNames[441] = "objTitleCloud1";
global.__objectNames[442] = "objCharacterSelect";
global.__objectNames[443] = "objLevelSelect";
global.__objectNames[444] = "objSelector";
global.__objectNames[445] = "objTitlescreenPlane";
global.__objectNames[446] = "objTitleWater";
global.__objectNames[447] = "objFade";
global.__objectNames[448] = "objSSToLevel";
global.__objectNames[449] = "objLevelToSS";
global.__objectNames[450] = "objFadeWhite";
global.__objectNames[451] = "objFadeWhiteFromSave";
global.__objectNames[452] = "objEnterUFO";
global.__objectNames[453] = "objEnterFFZ";
global.__objectNames[454] = "objEnterTTZF";
global.__objectNames[455] = "objCloudTransition";
global.__objectNames[456] = "objTTZ2Transition";
global.__objectNames[457] = "objGameOver";
global.__objectNames[458] = "objTimeTravel";
global.__objectNames[459] = "objTitlecard";
global.__objectNames[460] = "objTitlecardDisolve";
global.__objectNames[461] = "objTitleCardSSZ";
global.__objectNames[462] = "objTitleCardFFZ";
global.__objectNames[463] = "objTransition";
global.__objectNames[464] = "objSSZEndTransition";
global.__objectNames[465] = "objFinalEnding";
global.__objectNames[466] = "objEndingTransition";
global.__objectNames[467] = "objHud";
global.__objectNames[468] = "objParallax";
global.__objectNames[469] = "objThanksControl";
global.__objectNames[470] = "objScoreCard";
global.__objectNames[471] = "objSaveSlot";
global.__objectNames[472] = "objDeleteSlot";
global.__objectNames[473] = "objSaveControl";
global.__objectNames[474] = "obj3DSlant";
global.__objectNames[475] = "objLevel";
global.__objectNames[476] = "objSSPlayer";
global.__objectNames[477] = "objSSCamera";
global.__objectNames[478] = "Solid";
global.__objectNames[479] = "objSSLevel";
global.__objectNames[480] = "objSSCaterminatorOrb";
global.__objectNames[481] = "objSSOrbinautOrb";
global.__objectNames[482] = "objSSOrbinaut";
global.__objectNames[483] = "obj3DExplosion";
global.__objectNames[484] = "objSSCaterminator";
global.__objectNames[485] = "objSSEnemy";
global.__objectNames[486] = "objSSMoleMissile";
global.__objectNames[487] = "objMissileFire";
global.__objectNames[488] = "objSSMole";
global.__objectNames[489] = "objSSWhalebot";
global.__objectNames[490] = "objSSHud";
global.__objectNames[491] = "objSSScoreCard";
global.__objectNames[492] = "objSSMessages";
global.__objectNames[493] = "objSSRing";
global.__objectNames[494] = "objSSRingFly";
global.__objectNames[495] = "objSSBumper";
global.__objectNames[496] = "objSSSpikeBall";
global.__objectNames[497] = "objSSLargeSpike";
global.__objectNames[498] = "objSSMetalSonic";
global.__objectNames[499] = "obj3DShadow";
global.__objectNames[500] = "objSSLife";
global.__objectNames[501] = "objTrack";
global.__objectNames[502] = "objSSParent";
global.__objectNames[503] = "objSSEnd";
global.__objectNames[504] = "objSSEmerald";
global.__objectNames[505] = "objSSFutureTrack1_1";
global.__objectNames[506] = "objSSFutureTrack1_2";
global.__objectNames[507] = "objSSFutureTrack2_1";
global.__objectNames[508] = "objSSFutureTrack2_2";
global.__objectNames[509] = "objSSFutureTrack3_1";
global.__objectNames[510] = "objSSFutureTrack3_2";
global.__objectNames[511] = "objSSFutureTrack4_1";
global.__objectNames[512] = "objSSFutureTrack4_2";
global.__objectNames[513] = "objSSFutureTrack5_1";
global.__objectNames[514] = "objSSFutureTrack5_2";
global.__objectNames[515] = "objSSFutureTrack6_1";
global.__objectNames[516] = "objSSFutureTrack6_2";
global.__objectNames[517] = "objSSFutureTrack7_1";
global.__objectNames[518] = "objSSFutureTrack7_2";
global.__objectNames[519] = "objSSPastTrack1_1";
global.__objectNames[520] = "objSSPastTrack1_2";
global.__objectNames[521] = "objSSPastTrack2_1";
global.__objectNames[522] = "objSSPastTrack2_2";
global.__objectNames[523] = "objSSPastTrack3_1";
global.__objectNames[524] = "objSSPastTrack3_2";
global.__objectNames[525] = "objSSPastTrack4_1";
global.__objectNames[526] = "objSSPastTrack4_2";
global.__objectNames[527] = "objSSPastTrack5_1";
global.__objectNames[528] = "objSSPastTrack5_2";
global.__objectNames[529] = "objSSPastTrack6_1";
global.__objectNames[530] = "objSSPastTrack6_2";
global.__objectNames[531] = "objSSPastTrack7_1";
global.__objectNames[532] = "objSSPastTrack7_2";
global.__objectNames[533] = "objSSPastTrack1BG";
global.__objectNames[534] = "objSSBoost";
global.__objectNames[535] = "objPathSplitStall";
global.__objectNames[536] = "objNonSolid";
global.__objectNames[537] = "objSceneObject";
global.__objectNames[538] = "objSolid";
global.__objectNames[539] = "objShieldIce";
global.__objectNames[540] = "objShieldIceAttack";
global.__objectNames[541] = "objShieldIceBlockDebris";
global.__objectNames[542] = "objShieldBubble";
global.__objectNames[543] = "objShieldFlame";
global.__objectNames[544] = "objShieldLightning";
global.__objectNames[545] = "objShieldWind";
global.__objectNames[546] = "objShieldEarth";
global.__objectNames[547] = "objShieldEarth_Rock";
global.__objectNames[548] = "objDashSmoke";
global.__objectNames[549] = "objInstaShield";
global.__objectNames[550] = "objInvincibility";
global.__objectNames[551] = "objShield";
global.__objectNames[552] = "objTailsEffect";
global.__objectNames[553] = "objFallHat";
global.__objectNames[554] = "objCamera";
global.__objectNames[555] = "objEffect";
global.__objectNames[556] = "objPlayer";
global.__objectNames[557] = "objDustCloud";
global.__objectNames[558] = "objIntro1Control";
global.__objectNames[559] = "objIntroClouds";
global.__objectNames[560] = "objIntroIsland";
global.__objectNames[561] = "objIntroLittlePlanet";
global.__objectNames[562] = "objIntroMetalBack";
global.__objectNames[563] = "objIntroMetalFly";
global.__objectNames[564] = "objIntroMetalProfile";
global.__objectNames[565] = "objIntroMetalZoom";
global.__objectNames[566] = "objIntroSonicRunForward";
global.__objectNames[567] = "objPyramid";
global.__objectNames[568] = "objPyramidBack";
global.__objectNames[569] = "objPyramidRotate";
global.__objectNames[570] = "objMetalBackFull";
global.__objectNames[571] = "objPyramidJump";
global.__objectNames[572] = "objCutsceneController";
global.__objectNames[573] = "objBadnikCutscene";
global.__objectNames[574] = "objSonicLight";
global.__objectNames[575] = "objTailsLight";
global.__objectNames[576] = "objKnucklesLight";
global.__objectNames[577] = "objSonicIntroPast";
global.__objectNames[578] = "objKnucklesIntroPast";
global.__objectNames[579] = "objTailsIntroPast";
global.__objectNames[580] = "objIntroIslandPast";
global.__objectNames[581] = "objRobotnikPastIntro";
global.__objectNames[582] = "objDeathEggCut";
global.__objectNames[583] = "objSmallSonic";
global.__objectNames[584] = "objCutEmeralds";
global.__objectNames[585] = "objSonicKnuckles";
global.__objectNames[586] = "objTailsFlyCut";
global.__objectNames[587] = "objMetalSonicWarped";
global.__objectNames[588] = "objFadeInWhite";
global.__objectNames[589] = "objTimeTravelVortex";
global.__objectNames[590] = "objGalanikFloat";
global.__objectNames[591] = "objCharacterFall";
global.__objectNames[592] = "objLittlePlanetPiece1";
global.__objectNames[593] = "objBiPlane";
global.__objectNames[594] = "objCredits";
global.__objectNames[595] = "objEndingClouds";
global.__objectNames[596] = "objNeverLakeEnding";
global.__objectNames[597] = "objPlaneRestoreFinal";
global.__objectNames[598] = "objLittlePlanetPiece3";
global.__objectNames[599] = "objLittlePlanetPiece2";
global.__objectNames[600] = "objGalanikBadEnding";
global.__objectNames[601] = "objTextEnding";
global.__objectNames[602] = "objTLPRestoreEnding";
global.__objectNames[603] = "objMetalElectric";
global.__objectNames[604] = "objAmyEnding";
global.__objectNames[605] = "objEndingExplode";
global.__objectNames[606] = "objGalacnikFootPart";
global.__objectNames[607] = "objGalacnikStatchPart";
global.__objectNames[608] = "objGalacnikHandPart";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for